### ISSUE TITLE
Blank screenshot or incorrect settings

### ISSUE THREAD

**Issue by BrunoGysin** [jpxue/Overwatch-Aim-Assist#1]
I tested using vs2015, only made some changes to work here, but it is absurd lag and delay to detect.

the project is good, it should be based on the hack soldier82:
https://soldier82.com/

he and based on red-bordered set for the first shot after the first hit, it fits the hp bar.

here gif ONLY detect HP Bar:
https://i.imgur.com/8NfMjo3.gif

here gif red-bordered AND HP Bar:
https://i.imgur.com/sbevqBf.gif
yellow line: probably an enemy.
Red line: enemy according to the hp bar

multiples targets:
https://i.imgur.com/hvT20Ah.gif

program:
https://i.imgur.com/1UaIhQr.png
https://i.imgur.com/E17pQRi.png

probably used [opencv](http://opencv.org/).

OpenCV:
http://imgur.com/YDgBwXT
http://imgur.com/F1LHNbz

I created something with opencv to detect the contours, and even the bar. but I do not know much of opencv.

thank you for the source files.

**Comment by jpxue** [comment]
What changes did you specifically make?
You must be running in debug mode (should be in release) and on a toaster.

My hardware is pretty old and I run this on constant 70 FPS even while recording, proof: https://www.youtube.com/watch?v=0Su_ytp4-7I&feature=youtu.be
_I am using moveTo and not moveSmoothAuto in that video_

It takes me 50ms to scan 1920x1080 pixels for a target. Proof: http://i.imgur.com/XxgJS9U.jpg
I've included a timer class to measure this in the code itself. Most of the time taken is to capture the screenshot itself because the main algorithm (finding the target) only takes 8ms out of the 50ms. 

If you want to improve this you can get a screenshot by reading directly from the back buffer by hooking into EndScene, I'd however imagine this to drain your FPS even more so it might not be for you. You can also modify it to only scan for a particular area/FOV; currently it scans for the whole screen.

I've tried openCV by converting the image to HSV and using canny and findcontours to find the primary target without the need for health bars but I haven't found a way to fully exclude clusters of red pixels in the background and I haven't got the time to continue anyway.

**Comment by BrunoGysin** [comment]
It is in debug mode, in release ends up giving several errors.
I took the source without any changes, the only change was:

```
//======   AIMBOT   ======//
        if (screeny.findPlayer(x, y, false)) { //set to true if you aim headshots
            //mousey.moveSmoothAuto(x, y); //use moveTo for aimbot like movements
            cout << x << " " << y;
        }
```

I caught soldier 76 and hit several, back in 'cmd' and nothing appeared.

my test OpenCV:
http://i.imgur.com/ZURYA9Z.gif

thx

**Comment by jpxue** [comment]
STL is really slow in debug mode because it can generate an insane amount of overhead. It is not crippling in my experience, but release builds are about 2x faster.

What errors are you obtaining? The only thing that comes to mind is using _CRT_SECURE_NO_WARNINGS in the preprocessor definitions because I like to use the old CRT functions which are depracated in VS.

**Comment by BrunoGysin** [comment]
http://i.imgur.com/28n1r2R.png
using _CRT_SECURE_NO_WARNINGS in the preprocessor definitions:
http://i.imgur.com/h9x6Dow.png

the first image are the functions that I changed the first time.:
FindWindow to FindWindowA

It found the ow, but does not work as it should.

**Comment by jpxue** [comment]
The latter is happening because your project is being built for UNICODE and is by default referencing the FindWindowW function. You can use the FindWindowA function as you just did but or go to Properties -> Config Properties -> General and change it from the  "Character Set" field. 

Are you running the game in **borderless windowed** mode? Without this the captured screenshot would be all black - I should include a function to check for all black screenshots but I'm assuming that people know how to read.

Are you firing the first shot? It needs the health bar to appear before it assists you with your aim.
Does it print any x and y coordinates with the cout function that you included? 
You should also uncomment the mouse movement function otherwise it does nothing.

If this is not the case you'll have to go in debug mode and see why it's not detecting health bars or border points; for instance, maybe you're playing in colour blind mode and the colours are completely different.
