### ISSUE TITLE
Getting in trouble,please send me compiled version

### ISSUE THREAD

**Issue by justsky97** [jpxue/Overwatch-Aim-Assist#13]
Hello Iam asian 
I cant understand visual basic 
So can you give me compiled version for me?
  justsky97@gmail.com     

Wait your reply

**Comment by justsky97** [comment]
Can you give me a solution?
1. 10. 9. 오후 10:07에 "JP Xuereb" notifications@github.com님이 작성:

**Comment by jpxue** [comment]
A compiled version from my end would not work because Overwatch will have a different window name (seeing that you're asian), which you will have to input yourself in the windowname global variable. I don't even know what sensitivity you run on.

Solution: https://github.com/jpxue/Overwatch-Aim-Assist/issues/12
