### ISSUE TITLE
Screen Lock doubt

### ISSUE THREAD

**Issue by emptysoul15** [jpxue/Overwatch-Aim-Assist#31]
Is it possible to have screen lock by the code? Since I use a bypass and I still get screenblock
The colors change from nothing in the game and ready :( solution?

**Comment by jpxue** [comment]
Yes, I've noticed that they change the colors slightly if you bypass their screenlock and still use sendinput/mouse_event (I do not know if this is what you were referring to).

I don't know what 'bypass' you are using but obtaining a screenshot from the backbuffer should ALWAYS  work and I doubt they will be able to patch this easily because it would ruin video game recording software.
