### ISSUE TITLE
How do I aim my teammates?

### ISSUE THREAD

**Issue by Agenlone1y2016** [jpxue/Overwatch-Aim-Assist#33]
The Health Bar of teammates will always exist. (Settings: Show teammate Health Bar)
So program can always find out the teammates, then you can aim them.
How can I modify the program to bring this purpose? （Just change the RGB Values of teammates? What's them? And teammates has the different Health Bar. But the name of the teammate is fixed. Can I only search for the name?  )
That's important for an Anna player.
I am a C++ beginner.
Can you tell me how to do that?
Thanks!

**Comment by Agenlone1y2016** [comment]
By the way, Blizzard gave me a screen lock, how do I bypasses them?

**Comment by jpxue** [comment]
I would assume that the principle is still similar, find FRIENDLY player health bars (clusters of white?).
Once you find the health bar determine how much health player has, you can do this by scanning horizontally for HSV ranges that are of a typical health bar (hue+sats). From there on just use simple proportion to determine health % given that you know that width of a normally full health bar (I believe it is ~150?) and continue from there.

I address bypassing screen locks here:
https://github.com/jpxue/Overwatch-Aim-Assist/issues/30
https://github.com/jpxue/Overwatch-Aim-Assist/issues/29

**Comment by Agenlone1y2016** [comment]
Can you give me specific code?
I don't know anything.
Can you update the repository?

**Comment by jpxue** [comment]
I stopped developing this and the code that I have that addresses your issue are in other projects which I do not intend to publish (didn't write the code with publishing in mind).

What can't you understand? I do not mean to come across as condescending, but if you are expecting full-fledged copy/paste solutions to your problem without putting any effort in yourself then you will find no one that's willing to help you.

**Comment by Agenlone1y2016** [comment]
OK..Sorry
Which part of the code should I modify?

**Comment by jpxue** [comment]
For Ana bot you mean? You don't have to modify code (you can but not necessary) just write a new function that searches for a white clusters of pixels that correspond to the friendly player's health bar, you can base it off Screenshot::findPlayer() but can just exclude the part of the code that scans for the player's border and use offsets like in other bots.
Once you complete that function, call it and apply whatever logic you want to it.

White health bar pixels are slightly different from the red health bar pixels which are always 255,0,19 but if you apply a tolerance (similar to Screenshot::isRed()) you can get away with this, or just use HSV values (you can use Qt with the QColor class if you don't want to define HSV classes yourself).
Working with HSV is extremely helpful (built another project with HSV and achieved MUCH more).

For the bypass it depends on what route you're going to take which I explained in one of the links (mouse driver? d3d hook? setwindowsaffinity?).

**Comment by Agenlone1y2016** [comment]
Is HSV this?(OpenCV?)
![image](https://user-images.githubusercontent.com/35143699/51256909-7b640800-19e1-11e9-966b-af8312d43fcd.png)

But the 255,0,19 is the red health bar, can you tell me the white health bar value?
I can't understand the Screenshot::findPlayer codes.
Where should I modify in the code?

And how to fix the triggerBot? (You can answer this question if you want)

**Comment by jpxue** [comment]
_"I can't understand the Screenshot::findPlayer codes."_
Good to know I was wasting my time.
You need to learn C++ then because the code in findPlayer() is **extremely basic** C (variables, loops, branching statements). You cannot modify any code if you don't know how to program and I am wasting my time by answer your questions (even if I gave you the most in depth answer you wouldn't be able to implement any changes).

_"Can you tell me the white health bar value"_
You mean to tell me you don't know how to press print screen, paste it into paint and use the colour picker to get RGB values for your white colour? 

_"Is HSV this?(OpenCV?)"_
OpenCV supports HSV too yes as do MANY libraries. HSV is simply a construct encompassing 3 numbers, Hue, Saturation, Brightness with hue being the most useful number in our case (coupled with sat too) as a single number (spanning from 0-360) will tell you what the colour is. For white pixels saturation+brightness is also important. 

Start of with to find out what HSV is and to find how to get RGB values: https://www.youtube.com/watch?v=Tdcsqd1RnMw

**Comment by Agenlone1y2016** [comment]
> You mean to tell me you don't know how to press print screen, paste it into paint and use the colour picker to get RGB values for your white colour?

I tried it! But they are transparent, I can't get accurate values. (By ColorCop)

I have studied C++, but I am not studied it too deep.
I also want to improve my Programming skills.

I have studied C++, but I am not studied it too deep.
I also want to improve my Programming skills very much.

At last, thanks for your help!
Thank you for spending precious time on me.
I will study hard to learn programming to improve my Programming skills.
When I have achieved, I may contact you again.
Can I ask you questions when I encounter other problems on the road of knowledge?

Please close this issues.
