### ISSUE TITLE
To Find the Players Name Tag

### ISSUE THREAD

**Issue by spoofjack** [jpxue/Overwatch-Aim-Assist#8]
Is everyone just grabbing and running? Or trying to keep this private?

**Comment by jpxue** [comment]
A person did make some minor changes via a pull request which were really good, but I did not see them in time and had made a bunch of commits, stupid me :(.

I doubt people will be ready to share things unless they make a buck off it to be honest; just take a look at the overwatch market section in ownedcore and you'll see what I mean.

**Comment by spoofjack** [comment]
Sad but true. Yes @ParasiteEve had some changes he was making and updating quite often. He took his Repo to private and disappeared.

**Comment by spoofjack** [comment]
Couldn't We use this same Search for health bar method,

```
//Scans from top -> down. Move right -> reset
for (int i = length-width; x<width; i -= width) //x is changed inside
{
    if (isHealth(pixels[i])) //if pixel = health bar
```

To Find the Players Name Tag? Another Static Red Pixel. Check Out Picture. 

![overwatch 2016 10 02 - 23 51 06 01](https://cloud.githubusercontent.com/assets/20948932/19083183/2d2723be-8a2f-11e6-8898-37e4683b14ad.gif)

**Comment by spoofjack** [comment]
Now you eliminate the need for first hit. The only difficult thing to overcome would be how wide to go for name sack on battle tags.

**Comment by spoofjack** [comment]
Interesting Open CV Use

https://github.com/ahmetabdi/OverwatchCV

**Comment by jpxue** [comment]
Sorry for the late reply, bit busy right now.

I actually tried OpenCV and I adopted the same exact solution i.e. converting to HSV (this is mandatory for inRange) inRange (scan for yellow pixels - red pixels get converted to yellow) and findContours. 
Problem with this approach are mainly two:
#1: Maps are usually full of clusters of red pixels of all sizes, example: take the [capture point](http://cdn.blizzardwatch.com/wp-content/uploads/2016/04/anubis-1.jpg) in each map (notice the red sqaure on the ground) or maps such as route 66 (mountains are red/orange) - thus you will end up with A LOT of contours of all sorts of size that are not part of the player entity.
#2: The border around a player is more often than not incomplete, so you'll end up with small fragments of contours which need to be 'stitched' up in order to accurately deduce the player's coordinates.
#3:  Takes longer seeing that we're doing a lot more things such as namely converting to HSV and finding contours (I forgot how much MS it takes; it's not super long but there's an appreciable difference). My approach is a lot simpler and thus takes less time.

Naturally, these are all obstacles that can be overcome but I'd rather opt for a simple solution.

The reason why health bars are being used is for the simple reason that the pixels in a health bar itself have a constant RGB value (255,0,19). So once you find such a pixel you can assume that you've found a player close to that point and thus scan below it for something (which is in this case the border).

Reason why I am not using the name tags is because unlike health bars, the pixels within a nametag do not have a constant RGB value so once I find a red pixel I cannot tell if it's a border, part of the nametag itself, part of the background, part of the red square in every capture point, part of the timer (a red bar), part of the player's own weapon etc...
